/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_htssoft_simmons_Spawn */

#ifndef _Included_com_htssoft_simmons_Spawn
#define _Included_com_htssoft_simmons_Spawn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_htssoft_simmons_Spawn
 * Method:    backgroundSpawn
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_htssoft_simmons_Spawn_backgroundSpawn
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_htssoft_simmons_Spawn
 * Method:    backgroundWindowsSpawn
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_htssoft_simmons_Spawn_backgroundWindowsSpawn
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
